
export function userStudentType() {
    let studentChoose = [ 
        // { value: '0', show: '非離島' }, 
        { value: '1', show: '連江' }, 
        { value: '2', show: '金門' }, 
        { value: '3', show: '澎湖'}, 
        { value: '4', show: '綠島'}, 
        { value: '5', show: '琉球'}, 
        { value: '6', show: '願景'}, 
        { value: '7', show: '原住民'}, 
        { value: '8', show: '台東縣'}, 
        { value: '9', show:  '屏東縣'}, 
        { value: '10', show: '離島'},
        { value: '101', show: '鋼琴' }, 
        { value: '102', show: '聲樂' }, 
        { value: '103', show: '小提琴' }, 
        { value: '104', show: '中提琴' }, 
        { value: '105', show: '大提琴' },   
        { value: '106', show: '低音提琴' }, 
        { value: '107', show: '豎琴' }, 
        { value: '108', show: '古典吉他' }, 
        { value: '109', show: '長號' }, 
        { value: '110', show: '小號' }, 
        { value: '111', show: '法國號' }, 
        { value: '112', show: '上低音號' }, 
        { value: '113', show: '低音號' }, 
        { value: '114', show: '薩克斯管' }, 
        { value: '115', show: '長笛' }, 
        { value: '116', show: '單簧管(豎笛)' }, 
        { value: '117', show: '雙簧管' },
        { value: '118', show: '低音管' },
        { value: '119', show: '直笛' },
        { value: '120', show: '擊樂' },
        { value: '121', show: '理論作曲' },
        { value: '122', show: '南胡' },
        { value: '123', show: '琵琶' },
        { value: '124', show: '箏' },
        { value: '125', show: '笙' },
        { value: '126', show: '笛' },
        { value: '201', show: '籃球(男)' },
        { value: '202', show: '排球(男)' },
        { value: '203', show: '排球(女)' },
        { value: '204', show: '網球(男)' },
        { value: '205', show: '軟式網球(男)' },
        { value: '206', show: '軟式網球(女)' },
        { value: '207', show: '羽球(男)' },
        { value: '208', show: '羽球(女)' },
        { value: '209', show: '桌球(男)' },
        { value: '210', show: '桌球(女)' },
        { value: '211', show: '輕艇(男)' },
        { value: '212', show: '輕艇(女)' },
        { value: '213', show: '水上運動(女)' },
        { value: '214', show: '競技游泳(男)' },
        { value: '215', show: '競技游泳(女)' },
        { value: '216', show: '田徑(男)' },
        { value: '217', show: '田徑(女)' },
        { value: '218', show: '民俗體育(女)' },
        { value: '219', show: '巧固球(男)' },
        { value: '220', show: '巧固球(女)' },
        { value: '221', show: '籃球' },
        { value: '222', show: '排球' },
        { value: '223', show: '體操' },
        { value: '224', show: '滾球' },
        { value: '225', show: '術與龍獅運動' },
        { value: '226', show: '足球' },
        { value: '227', show: '五人制足球' },

        
      ]

  return {
    studentChoose
  };
}